use etec_teste_2;

/*
PROCEDIMENTO UTILIZADO PARA PRÉ CADASTRAR, GERANDO AUTOMATICAMENTE O PROTOCOLO PARA HANDSHAKE.
*/



DELIMITER $$
CREATE PROCEDURE USP_PRE_CADASTRO(IN NOME VARCHAR(120), IN EMAIL VARCHAR(120), IN CPF VARCHAR(14), 
IN CODETEC INT, IN IDPERFIL INT, IN IDCURSO INT, IN SEMESTRE INT, OUT PROTOCOLO VARCHAR(20))
BEGIN

	DECLARE exception SMALLINT DEFAULT 0;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET exception = 1;

 
    START TRANSACTION;

    SET PROTOCOLO = concat(CODETEC, date_format(NOW(), "%Y%m%d%H%i%s"),"-", substr(CPF, -2) );
    IF exception = 1
    THEN
      SELECT 'Erro ao Gerar Protocolo' AS Msg;
      ROLLBACK;
    ELSE
    
    INSERT INTO PESSOA (PESSOA_NOME, PESSOA_EMAIL, PESSOA_CPF, PESSOA_DATA_CADASTRO, 
						PESSOA_PROTOCOLO, ID_PERFIL)
	VALUES
						(NOME,EMAIL, CPF, NOW(), PROTOCOLO, IDPERFIL );
    
    IF exception = 1
    THEN
      SELECT 'Erro ao inserir Pessoa' AS Msg;
      ROLLBACK;
    ELSE
    SELECT DISTINCT LAST_INSERT_ID() INTO @idPessoa FROM PESSOA;
    
    IF exception = 1
      THEN
        SELECT 'Erro ao selecionar o ID' AS Msg;
        ROLLBACK;
	ELSE
    
	INSERT INTO PESSOA_CURSO (ID_PESSOA, ID_CURSO, PESSOA_CURSO_SEMESTRE) VALUES (@idPessoa, IDCURSO, SEMESTRE);
    IF exception = 1
        THEN
          SELECT 'Erro ao inserir na tabela Pessoa Curso' AS Msg;
          ROLLBACK;
        ELSE
         SELECT PROTOCOLO;
     COMMIT;
     
        END IF;
      END IF;
    END IF;
    END IF;
    

  
END $$
DELIMITER ;



DELIMITER $$
CREATE PROCEDURE USP_COMPLETACADASTRO(IN APELIDO VARCHAR(20),
 IN USUARIO VARCHAR(30), IN SENHA VARCHAR(20), IN CELULAR VARCHAR(15), IN DESCRICAOPERFIL VARCHAR(255), 
 IN PROTOCOLO VARCHAR(20), OUT PESSOAID INT)
BEGIN

	DECLARE exception SMALLINT DEFAULT 0;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET exception = 1;
 
    START TRANSACTION;

SELECT DISTINCT
    PESSOA_ID
INTO @idPessoa FROM
    PESSOA
WHERE
    PESSOA_PROTOCOLO = PROTOCOLO;
IF exception = 1
    THEN
      SELECT 'Erro ao recuperar ID' AS Msg;
      ROLLBACK;
    ELSE

UPDATE PESSOA SET PESSOA_APELIDO = APELIDO, PESSOA_USUARIO = USUARIO, PESSOA_SENHA=SENHA, PESSOA_CELULAR = CELULAR,
 PESSOA_DESCPERFIL = DESCRICAOPERFIL, PESSOA_DATA_ALTERACAO = NOW(), PESSOA_STATUS = "ATIVO",
 PESSOA_OBSERVACOES = concat("Cadastro completado em ", date_format(NOW(), "%d/%m/%Y")) WHERE PESSOA_ID = @idPessoa;
IF exception = 1
    THEN
      SELECT 'Erro ao Alterar Pessoa' AS Msg;
      ROLLBACK;
    ELSE
    COMMIT;
    
SELECT @idPessoa;
    
    END IF;
   END IF;
    

END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_ATIVIDADES(IN COD_ETEC BIGINT, PAGINACAO INT)
BEGIN

SELECT *
 FROM HISTORICO_DESAFIO HD 
 INNER JOIN GRUPO GR ON GR.GRUPO_ID = HD.GRUPO_ID 
 WHERE GR.ID_ETEC = COD_ETEC ORDER BY HISTORICO_ID DESC LIMIT PAGINACAO, 10;

END $$
DELIMITER ;



DELIMITER $$
CREATE PROCEDURE USP_COMENTARIOS(IN COD_ETEC BIGINT, PAGINACAO INT)
BEGIN

INSERT INTO COMENTARIO (COMENTARIO, COMENTARIO_DATA, ID_DESAFIO, ID_COMENTARIO,)

END $$
DELIMITER ;


call USP_PRE_CADASTRO('Alex Santos', 'contato@santocodigo.com.br','399.305.868-22', 1, 2, 1, 3, @protocolo);

call USP_COMPLETACADASTRO('Alex', 'alex', 'alex123', '(11) 966953835', 'Gosto de Batata', '120180504140752-22', @IdPessoa);

